export const Avatars = [
  { icon: "person-outline", color: "#FF5733" },
  { icon: "happy-outline", color: "#33FF57" },
  { icon: "glasses-outline", color: "#3357FF" },
  { icon: "baseball-outline", color: "#FF33A8" },
  { icon: "football-outline", color: "#33FFF5" },
  { icon: "basketball-outline", color: "#F533FF" },
  { icon: "person-circle-outline", color: "#FFB533" },
  { icon: "planet-outline", color: "#33FFBD" },
  { icon: "moon-outline", color: "#8A33FF" },
  { icon: "rocket-outline", color: "#FFA533" },
  { icon: "game-controller-outline", color: "#33FFE0" },
  { icon: "headset-outline", color: "#FF33E8" },
  { icon: "heart-outline", color: "#FF3333" },
  { icon: "diamond-outline", color: "#33A8FF" },
  { icon: "star-outline", color: "#FFD700" },
  { icon: "paw-outline", color: "#8B4513" },
  { icon: "musical-notes-outline", color: "#9933FF" },
  { icon: "camera-outline", color: "#33FF99" },
  { icon: "cafe-outline", color: "#A0522D" },
  { icon: "beer-outline", color: "#FFC733" },
];
